# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 02:34
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSingle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=blog.models.ImageSingle.get_upload_path)),
            ],
            options={
                'verbose_name_plural': 'ImageSingles',
                'verbose_name': 'ImageSingle',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=blog.models.Post.get_upload_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(),
        ),
    ]
