# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160108_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_thumbnail',
        ),
    ]
