# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160114_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallink',
            name='internal',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='headline',
            name='smart_link',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.ExternalLink'),
        ),
    ]
