# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160113_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadlineCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'HeadlineCycle',
                'verbose_name_plural': 'HeadlineCycles',
            },
        ),
        migrations.AddField(
            model_name='headline',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headline',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.HeadlineCycle'),
        ),
    ]
