# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20151205_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='id_post',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
