# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 12:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160113_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 13, 12, 45, 44, 791165, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
