# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160114_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='smart_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.ExternalLink'),
        ),
    ]
