# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 08:34
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20151212_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSingle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=blog.models.ImageSingle.get_upload_path)),
            ],
            options={
                'verbose_name': 'ImageSingle',
                'verbose_name_plural': 'ImageSingles',
            },
        ),
        migrations.CreateModel(
            name='Typo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
            options={
                'verbose_name': 'Typo',
                'verbose_name_plural': 'Typos',
            },
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
