# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_headline_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
