# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 09:57
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_subscribeemail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribeemail',
            options={'verbose_name': 'SubscribeEmail', 'verbose_name_plural': 'SubscribeEmails'},
        ),
        migrations.AddField(
            model_name='post',
            name='image_thumbnail',
            field=models.ImageField(null=True, upload_to=blog.models.Post.get_upload_path),
        ),
    ]
