# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 09:58
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20151225_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.Post.get_upload_path),
        ),
    ]
