# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='id_question',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
