# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hunt.Profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='makers',
            field=models.ManyToManyField(blank=True, related_name='post_makers', to='hunt.Profile'),
        ),
    ]
