# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0002_auto_20160125_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_create',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
