# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0003_post_date_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='tf'),
            preserve_default=False,
        ),
    ]
