# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0005_auto_20160128_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_profile',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='post_upvotes', to='hunt.Profile'),
        ),
    ]
