# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0007_auto_20160130_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upvotes_count',
            field=models.IntegerField(default=1),
        ),
    ]
