# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0008_post_upvotes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type_profile',
            field=models.CharField(choices=[('active', 'Active'), ('no_active', 'No Active')], default='no_active', max_length=20),
        ),
    ]
