# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0009_profile_type_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_create',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comment',
            name='time_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(verbose_name='Ссылка на сайт'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название стартапа'),
        ),
    ]
