# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0011_invite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='not_used',
        ),
    ]
