# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0012_remove_invite_not_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='text',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
