# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextContent',
        ),
    ]
