# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_textcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='textcontent',
            name='content',
            field=models.FileField(null=True, upload_to='files'),
        ),
    ]
